FROM debian

RUN apt-get update && apt-get install -y cmake=3.5
# RUN apt-get update && \
#  apt-get install -y cmake libgflags-dev liblog4cxx-dev libomp-dev libeigen3-dev git

# RUN git clone https://github.com/xptree/NetSMF.git && cd NetSMF && mkdir build && ./configure && cd build && make

# RUN R -e "devtools::install_github('ebenmichael/augsynth')"
# WORKDIR /home/app
# COPY rs_mwe.r /home/app/rs_mwe.r
# RUN Rscript rs_mwe.r
