FROM jupyter/datascience-notebook

USER root
WORKDIR /apps

RUN apt update
# RUN apt install -y zip wget build-essential python3-dev libkrb5-dev libxml2-dev

# add python packages
RUN conda update --all

# RUN chmod -R a+rw /home/jovyan
