FROM redhat/ubi8

RUN yum update && yum install -y wget unzip

# install odbc driver
RUN wget https://s3.amazonaws.com/athena-downloads/drivers/ODBC/SimbaAthenaODBC_1.1.18.1001/Linux/simbaathena-1.1.18.1001-1.el7.x86_64.rpm
RUN rpm -i simbaathena-1.1.18.1001-1.el7.x86_64.rpm

# install aws cli
RUN wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
RUN unzip awscli-exe-linux-x86_64.zip
RUN ./aws/install

# install athena odbc connector
RUN wget https://s3.amazonaws.com/athena-downloads/drivers/ODBC/SimbaAthenaODBC_1.1.18.1001/Linux/simbaathena-1.1.18.1001-1.el7.x86_64.rpm
RUN yum --nogpgcheck localinstall simbaathena-1.1.18.1001-1.el7.x86_64.rpm

# install python tools
# RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p ./miniconda3
# RUN ln /miniconda3/bin/conda /usr/local/bin/conda
# RUN conda init bash; bash
# RUN conda create -n aws-env python
# RUN conda install python pip
# RUN pip install aws-adfs
